spring.application.name=relmap-demo

spring.datasource.url=jdbc:h2:mem:data1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# App would auto-create tables from Entities
spring.jpa.hibernate.ddl-auto=create

